title: Vota Nessuno
description: Il partito della maggioranza silenziosa
url: "https://votanessuno.github.io"
lang: it
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
